.catalog:
  name: "netbox"
  version: v2-v1.8.4
  description: "Inventory tool"
  minimum_rancher_version: v1.1.9
  questions:
    - variable: mount_path
      description: "Leave on default unless important to change (ends without a /)"
      label: "Default mount path for persistent storage"
      required: true
      default: "/mnt/docker"
      type: "string"
