version: '2'
services:
  puppet:
    restart: unless-stopped
    hostname: puppet
    image: opsforge/puppetserver
    expose:
      - 8140
    volumes:
      - ${puppet_mount}/puppet-data/code:/etc/puppetlabs/code/
      - ${puppet_mount}/puppet-data/puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - ${puppet_mount}/puppet-data/puppet/environments:/etc/puppetlabs/puppet/environments/
      - ${puppet_mount}/puppet-data/puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/

  postgres:
    restart: unless-stopped
    hostname: postgres
    image: opsforge/puppetdb-psql
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - ${puppet_mount}/puppet-data/puppetdb-postgres/data:/var/lib/postgresql/data/

  puppetdb:
    restart: unless-stopped
    hostname: puppet.db
    image: opsforge/puppetdb
    expose:
      - 8080
      - 8081
    volumes:
      - ${puppet_mount}/puppet-data/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/

  puppetboard:
    restart: unless-stopped
    hostname: puppetboard
    image: opsforge/puppetboard
    expose:
      - 80
