puppet:
  restart: unless-stopped
  hostname: puppet
  image: opsforge/puppet3x
  expose:
    - 8140
    - 443
    - 8080
    - 8081
  volumes:
    - ${puppet_mount}/puppet-data/puppet/ssl:/var/lib/puppet/ssl
    - ${puppet_mount}/puppet-data/puppet/environments:/etc/puppet/environments

postgres:
  restart: unless-stopped
  hostname: postgres
  image: opsforge/puppetdb-psql
  environment:
    - POSTGRES_PASSWORD=puppetdb
    - POSTGRES_USER=puppetdb
  expose:
    - 5432
  volumes:
    - ${puppet_mount}/puppet-data/pgsql-data:/var/lib/postgresql/data/
